---
- name: Deploy and Configure Snort IDS
  hosts: localhost
  gather_facts: yes
  become: yes

  tasks:
    - name: Update apt cache and upgrade all packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: Ensure required packages are installed
      ansible.builtin.apt:
        name:
          - build-essential
          - libpcap-dev
          - libpcre3-dev
          - libdumbnet-dev
          - bison
          - flex
          - zlib1g-dev
          - liblzma-dev
          - libssl-dev
          - cmake
        state: present

  roles:
    - role: snort
