---
- name: Deploy and Configure Snort IDS
  hosts: localhost
  gather_facts: yes
  become: yes
  vars:
    home_net: "127.0.0.1"
    snort_rules_url: "https://www.snort.org/rules/community"
    snort_rules_path: "/etc/snort/rules"

  tasks:
    - name: Update apt cache and upgrade all packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: Ensure required packages are installed
      ansible.builtin.apt:
        name:
          - build-essential
          - libpcap-dev
          - libpcre3-dev
          - libdumbnet-dev
          - bison
          - flex
          - zlib1g-dev
          - liblzma-dev
          - libssl-dev
          - cmake
        state: present

  roles:
    - role: snort
      vars:
        home_net: "{{ home_net }}"
        external_net: "!{{ home_net }}"
        snort_rules_url: "{{ snort_rules_url }}"
        snort_rules_path: "{{ snort_rules_path }}"
