---
- name: Extract Snort 3 community rules
  unarchive:
    src: "{{ snort_rules_path }}/snort3-community-rules.tar.gz"
    dest: "{{ snort_rules_path }}/community"
    remote_src: yes
  listen: "Extract Snort rules"

- name: restart snort
  systemd:
    name: snort
    state: restarted
    enabled: yes

- name: reload snort
  systemd:
    name: snort
    state: reloaded
