---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  platforms:
  - name: instance-ubuntu
    image: "solita/ubuntu-systemd:latest"
    privileged: true
    command: "/sbin/init"
  - name: instance-ubuntu
    image: "ubuntu:latest"
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: /usr/bin/python3
verifier:
  name: ansible

