---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install Python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python3-minimal)
      changed_when: false
      become: yes

    - name: Create symlink for Python3
      raw: ln -s /usr/bin/python3 /usr/bin/python
      become: yes
      when: ansible_facts['ansible_python']['executable'] is not defined
